### ISSUE TITLE
Which p12 cert do I need to convert?

### ISSUE THREAD

**Issue by XsylenZ** [arrowhead-f/client-cpp#6]
Hi, 

I was wondering which p12 certificate I need to convert to make it work?

I see that there is a script file where you create the PEM files from the client1.testcloud2.p12 file. I created my own Arrowhead system on a Debian machine. It creates a certificate for every core system and also a sysop.p12 cert. that I use now to connect with Chrome.

Which one do I need to use to make this example work for my system?

**Comment by sumi0910** [comment]
follow

**Comment by sumi0910** [comment]
Hello, can anyone tell which certificate needs to be used for c++ example to run

**Comment by tsvetlin** [comment]
You need to generate yourself a client certificate. 
https://github.com/arrowhead-f/core-java-spring/blob/master/documentation/certificates/create_client_certificate.pdf
