### ISSUE TITLE
confused regarding the certificate that needs to be used while running the c++ example

### ISSUE THREAD

**Issue by sumi0910** [arrowhead-f/client-cpp#7]
Hello, 

**which certificate needs to be used for c++ example to run as I have sysop.p12 being used by the arrowhead framework with the extension of sysop.testcloud.user.arrowhead.eu (followed debian installation ) but in keys folder, there are .pem files are generated based on testcloud1.p12 and also secure temperature sensor.testcloud2.airia.arrowhead.eu.p12 present in keys2 folder.** 

I am doing my thesis which requires working application system in C++ using Arrowhead framework 4.1.3 version. It would be really really helpful if I understand this example properly and I am kind of stuck with these certifications because working with 4.1.2 version was bit easy as there were not many complications with respect to security. But as per the development that is being supported for 4.1.3 version, had to use this and it is difficult to follow because of not more knowledge regarding certificate development and chain. Any kind of help towards understanding this would be appreciated.

**Comment by tottthy** [comment]
Hello,

The ConsumerExample and ProviderExample master branches are based on the keys2 folder. The master branch is compatible with the 4.1.3 version. It should be communicate with the test servers running on https://arrowhead.tmit.bme.hu. As the pem files indicate, the provider name should be "securetemperaturesensor". 
To create your own certificate, please read the following tutorial: https://github.com/arrowhead-f/core-java-spring/blob/master/README.md#certificates

The basic steps are:
1. Provider registration into the ServiceRegistry module
2. Consumer registration into the ServiceRegistry/systems (POST /serviceregistry/mgmt/systems)
3. Create a new database content in the Authorizer, using the proper HTTPs request with the required IDs. To get the proper IDs, you can use the following HTTPs requests:
System id: GET /serviceregistry/mgmt/systems
Interface id:  GET/serviceregistry/mgmt/grouped
Service ID: GET /serviceregistry/mgmt/services
4. Orchestration procedure

To use e.g. the swagger UI on the arrowhead.tmit.bme.hu servers in secure mode, the sysop.p12 should be added to Chrome or Firefox browsers.

I advise you to test the sources with the arrowhead.tmit.bme.hu servers. If the modules are not available, please contact with Szvetlin (szvetlin@aitia.ai).

**Comment by sumi0910** [comment]
Hello,
I generated the certificates that were required to access the framework. But I am getting an error
 "Error: Unknown URL: /socketcluster/
curl_easy_perform() failed: Couldn't connect to server"

The details of the configuration of ApplicationServiceInterface.ini is as follows
Server]
sr_base_uri_https="https://192.168.0.3:8443/serviceregistry/"
port="8000"
address="192.168.0.4"
address6="[fe80::ba27:ebff:fef9:1f8b]"
Accessing the url from Raspberry Pi to  https://192.168.0.3:8443/serviceregistry/ gives the below error
This site can’t provide a secure connection 192.168.0.3 didn’t accept your login certificate, or one may not have been provided.
Try contacting the system admin.
ERR_BAD_SSL_CLIENT_AUTH_CERT

**Is there any issue in setting up the server or is it related to certificate** 

Accessing the Swagger UI using securetemperaturesensor certificate in Raspberry Pi gives 
Service Registry found on echo (https://192.168.0.3:8443/swagger-ui.html#/All/echoServiceUsingGET)

**Comment by sumi0910** [comment]
@tottthy i figured out that the issue is w.r.t curl not finding the certificate chains... Now I am thinking about how it worked for you because in Applicationinterface.ini only https link works but curl throws an error that bad connection. It would be great help if you could let me know how these certificate chains are related w.r.t working with curl

**Comment by sumi0910** [comment]
At present I am getting Orchestration Response as {"response";[]}
Error: Could not parse provider section
*failed writing body (1!=15)
*failed writing dat
*curl_http_done: called premature==1
*stopped the pause stream!
*closing connection 0
Error: curl_easy_perform() failed: Failed writing received data to disk/application

*Any idea why is that so? I tried looking at SensorHandler.cpp to find the root cause and tried adding preferred providers in the consumedServices.json to understand if the issue is w.r.t provider but with no success. It would be appreciated if you could provide some kind of feedback to proceed with.*
